services:
  - type: web
    name: remotecamera
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: METERED_API_KEY
        sync: false
      - key: METERED_APP_NAME
        sync: false
